#!/usr/bin/env node
'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const {spawn}=require('child_process');
const runtime=require('./runtime').selectRuntime();
const ROOT=__dirname,WEB=path.join(ROOT,'web'),MAX=512*1024*1024,HOST=process.env.TRANSCRIPT_HOST||'0.0.0.0',PORT=Number(process.env.TRANSCRIPT_PORT||8124),THREADS=6,LEASE_MS=45000;
const MODEL=path.resolve(ROOT,'models',process.env.TRANSCRIPT_MODEL||'canary-1b-v2-q8_0.gguf'),EMBEDDER=path.join(ROOT,'models','wespeaker-resnet34-lm.gguf');
const VERSION=fs.existsSync(path.join(ROOT,'VERSION'))?fs.readFileSync(path.join(ROOT,'VERSION'),'utf8').trim():'development';
const jobs=new Map(),queue=[],tempDir=fs.mkdtempSync(path.join(os.tmpdir(),'canary-web-'));let running=null,speedFactor=runtime.speed;
function json(res,code,value){const body=JSON.stringify(value);res.writeHead(code,{'Content-Type':'application/json','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store'});res.end(body)}
function snapshot(job){const now=job.endedAt||Date.now(),elapsed=job.startedAt?(now-job.startedAt)/1000:0,estimate=job.duration>0&&speedFactor>0?job.duration/speedFactor+5:0;const progress=job.status==='queued'?0:job.status==='processing'?(estimate?Math.min(95,Math.round(elapsed/estimate*90+5)):null):100;return{version:VERSION,id:job.id,status:job.status,phase:job.phase,progress,elapsed:Math.round(elapsed),eta:job.status==='processing'&&estimate?Math.max(0,Math.round(estimate-elapsed)):null,audioAvailable:!!job.audioAvailable,result:job.result,error:job.error}}
function notify(job){const data=`data: ${JSON.stringify(snapshot(job))}\n\n`,terminal=['complete','error','cancelled'].includes(job.status);for(const client of [...job.clients]){client.write(data);if(terminal){client.end();job.clients.delete(client)}}}
function wordsOf(s){return(s.words||[]).map(w=>({text:String(w.text||''),start:Number(w.offsets?.from??Number(w.t0||0)*10)/1000,end:Number(w.offsets?.to??Number(w.t1||0)*10)/1000})).filter(w=>w.text)}
function repair(segments){for(let i=0;i+1<segments.length;i++){const left=segments[i],right=segments[i+1],lt=left.text.trim(),rt=right.text.trim();if(left.speaker===right.speaker||/[.!?…][\"”')\]]?$/.test(lt))continue;const prefix=rt.match(/^(.{1,120}?[.!?…][\"”')\]]?)(?:\s+|$)([\s\S]*)$/),tail=lt.match(/^([\s\S]*[.!?…][\"”')\]]?)\s+([^.!?…]{1,120})$/),pc=prefix?prefix[1].trim().split(/\s+/).length:Infinity,tc=tail?tail[2].trim().split(/\s+/).length:Infinity;if(tail&&tc<pc&&tc<=10){left.text=tail[1].trim();right.text=`${tail[2].trim()} ${rt}`;right.words.unshift(...left.words.splice(-tc))}else if(prefix&&pc<=10){left.text=`${lt} ${prefix[1].trim()}`;right.text=prefix[2].trim();left.words.push(...right.words.splice(0,pc))}}for(const s of segments){if(s.words.length){s.start=s.words[0].start;s.end=s.words.at(-1).end}}return segments.filter(s=>s.text.trim())}
function paragraphs(raw){const segments=raw.segments||raw.transcription||[],speech=segments.filter(s=>(s.text||'').trim());if(speech.length&&(!speech.some(s=>String(s.speaker||'').trim())||!speech.some(s=>Number(s.offsets?.to)>Number(s.offsets?.from))||!speech.some(s=>wordsOf(s).some(w=>w.end>w.start))))throw new Error('Transcription output is missing speaker labels or usable timestamps. Please transcribe again.');const source=repair((raw.segments||raw.transcription||[]).map(s=>({speaker:speakerLabel(s.speaker),text:s.text||'',start:Number(s.offsets?.from||0)/1000,end:Number(s.offsets?.to||0)/1000,words:wordsOf(s)}))),groups=[];for(const s of source){const speaker=s.speaker||'Unknown',text=s.text.trim(),last=groups.at(-1),gap=last?Number(s.start||0)-last.end:Infinity;if(last&&last.speaker===speaker&&gap<1.5){last.text+=` ${text}`;last.end=Number(s.end||last.end);last.words.push(...s.words)}else groups.push({speaker,start:Number(s.start||0),end:Number(s.end||0),text,words:s.words})}return{duration:raw.duration||groups.at(-1)?.end||0,language:raw.language||raw.crispasr?.language,text:groups.map(p=>`Speaker ${p.speaker} [${clock(p.start)}]\n${p.text}`).join('\n\n'),paragraphs:groups}}
function speakerLabel(value){const m=String(value||'').match(/speaker\s+(\d+)/i);if(!m)return String(value||'Unknown').trim();let n=Number(m[1]),label='';do{label=String.fromCharCode(65+n%26)+label;n=Math.floor(n/26)-1}while(n>=0);return label}
function clock(seconds){const s=Math.max(0,Math.floor(seconds)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),r=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`:`${m}:${String(r).padStart(2,'0')}`}
function release(job){if(!job.audioAvailable)return false;job.audioAvailable=false;job.leaseUntil=0;fs.rm(job.file,{force:true},()=>{});return true}
function next(){if(running||!queue.length)return;const job=queue.shift();running=job;job.status='processing';job.phase=`High-quality transcription and speaker detection (${runtime.label})`;job.startedAt=Date.now();job.outputBase=path.join(tempDir,`${job.id}.result`);notify(job);const output=`${job.outputBase}.json`,language=job.language==='auto'?'ro':job.language,bundled=fs.existsSync(MODEL)&&fs.existsSync(EMBEDDER),args=[...runtime.args,'--threads',String(THREADS),'--beam-size','1','--backend','canary','--model',bundled?MODEL:'auto',...(bundled?[]:['--auto-download']),'--file',job.file,'--language',language,'--source-lang',language,'--target-lang',language,'--no-auto-aligner','--diarize','--diarize-method','foxnose','--diarize-embedder',bundled?EMBEDDER:'auto',...(job.speakers>0?['--diarize-num-speakers',String(job.speakers)]:[]),'--output-json-full','--output-file',job.outputBase,'--no-prints'];const child=spawn(runtime.binary,args,{cwd:ROOT,env:runtime.env});job.child=child;let stderr='';child.stderr.on('data',d=>stderr+=d);child.on('close',(code,signal)=>{job.child=null;job.endedAt=Date.now();const seconds=(job.endedAt-job.startedAt)/1000;if(job.status==='cancelled'){fs.rm(job.file,{force:true},()=>{});fs.rm(output,{force:true},()=>{});running=null;notify(job);return next()}if(code!==0){fs.rm(job.file,{force:true},()=>{});job.status='error';const reason=signal?`Transcriber was stopped by signal ${signal}`:`Transcriber exited with code ${code}`;job.error=stderr.trim()?`${reason}. Details: ${stderr.trim()}`:reason}else try{job.result=paragraphs(JSON.parse(fs.readFileSync(output,'utf8')));job.status='complete';job.phase='Complete';job.audioAvailable=true;job.leaseUntil=Date.now()+LEASE_MS;if(job.duration>5&&seconds>0)speedFactor=speedFactor>0?speedFactor*.7+(job.duration/seconds)*.3:job.duration/seconds}catch(error){fs.rm(job.file,{force:true},()=>{});job.status='error';job.error=`Invalid transcription response: ${error.message}`}fs.rm(output,{force:true},()=>{});running=null;notify(job);next()})}
function create(req,res){const length=Number(req.headers['content-length']||0);if(!length)return json(res,411,{error:'Content-Length required'});if(length>MAX)return json(res,413,{error:'Maximum upload size is 512 MB'});const id=crypto.randomUUID(),original=decodeURIComponent(String(req.headers['x-filename']||'audio.wav')),ext=path.extname(original).replace(/[^.a-z0-9]/gi,'').slice(0,10)||'.audio',file=path.join(tempDir,`${id}${ext}`),job={id,file,original,status:'uploading',phase:'Receiving upload',duration:Number(req.headers['x-duration']||0),language:String(req.headers['x-language']||'auto'),speakers:Math.max(0,Math.min(8,Number(req.headers['x-speakers']||0))),clients:new Set(),audioAvailable:false};jobs.set(id,job);const out=fs.createWriteStream(file,{flags:'wx'});let received=0,failed=false,finished=false;const discard=()=>{if(finished)return;failed=true;out.destroy();fs.rm(file,{force:true},()=>{})};req.on('data',chunk=>{received+=chunk.length;if(received>MAX&&!failed){discard();req.destroy()}});req.on('aborted',discard);req.on('error',discard);req.pipe(out);out.on('finish',()=>{finished=true;if(failed)return fs.rm(file,{force:true},()=>{});job.status='queued';job.phase=running?'Waiting for current recording':'Starting';queue.push(job);json(res,202,{id});next()});out.on('error',error=>{fs.rm(file,{force:true},()=>{});if(!res.headersSent)json(res,500,{error:error.message})})}
function events(req,res,job){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache',Connection:'keep-alive'});res.write(`data: ${JSON.stringify(snapshot(job))}\n\n`);if(['complete','error','cancelled'].includes(job.status))return res.end();job.clients.add(res);const timer=setInterval(()=>notify(job),1000);req.on('close',()=>{clearInterval(timer);job.clients.delete(res)})}
function removeOrCancel(res,job){if(job.status==='complete'){release(job);return json(res,200,{status:'deleted'})}if(['error','cancelled'].includes(job.status))return json(res,200,{status:job.status});job.status='cancelled';job.phase='Cancelled';job.endedAt=Date.now();const child=job.child;if(child){child.kill('SIGTERM');setTimeout(()=>{if(job.child===child)child.kill('SIGKILL')},1000)}const i=queue.indexOf(job);if(i>=0)queue.splice(i,1);fs.rm(job.file,{force:true},()=>{});notify(job);json(res,200,{status:'cancelled'})}
function mime(file){return({'.mp3':'audio/mpeg','.wav':'audio/wav','.flac':'audio/flac','.ogg':'audio/ogg','.m4a':'audio/mp4','.aac':'audio/aac','.webm':'audio/webm'})[path.extname(file).toLowerCase()]||'application/octet-stream'}
function audio(req,res,job){if(!job.audioAvailable||!fs.existsSync(job.file))return json(res,410,{error:'Audio has been deleted'});job.leaseUntil=Date.now()+LEASE_MS;const size=fs.statSync(job.file).size,range=req.headers.range,headers={'Content-Type':mime(job.file),'Accept-Ranges':'bytes','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};let start=0,end=size-1,code=200;if(range){const m=range.match(/^bytes=(\d*)-(\d*)$/);if(!m){res.writeHead(416,{'Content-Range':`bytes */${size}`});return res.end()}if(m[1])start=Number(m[1]);if(m[2])end=Number(m[2]);if(start>end||start>=size){res.writeHead(416,{'Content-Range':`bytes */${size}`});return res.end()}end=Math.min(end,size-1);code=206;headers['Content-Range']=`bytes ${start}-${end}/${size}`}headers['Content-Length']=end-start+1;res.writeHead(code,headers);if(req.method==='HEAD')return res.end();fs.createReadStream(job.file,{start,end}).pipe(res)}
const server=http.createServer((req,res)=>{try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/api/version')return json(res,200,{version:VERSION});if(req.method==='POST'&&url.pathname==='/api/jobs')return create(req,res);const m=url.pathname.match(/^\/api\/jobs\/([0-9a-f-]+)(?:\/(events|audio|heartbeat|release))?$/);if(m){const job=jobs.get(m[1]);if(!job)return json(res,404,{error:'Job not found'});const action=m[2];if(req.method==='GET'&&action==='events')return events(req,res,job);if((req.method==='GET'||req.method==='HEAD')&&action==='audio')return audio(req,res,job);if(req.method==='POST'&&action==='heartbeat'){if(!job.audioAvailable)return json(res,410,{audioAvailable:false});job.leaseUntil=Date.now()+LEASE_MS;return json(res,200,{audioAvailable:true})}if(req.method==='POST'&&action==='release'){release(job);return json(res,200,{status:'deleted'})}if(req.method==='GET'&&!action)return json(res,200,snapshot(job));if(req.method==='DELETE'&&!action)return removeOrCancel(res,job)}if(req.method==='GET'&&(url.pathname==='/'||url.pathname==='/index.html')){const body=fs.readFileSync(path.join(WEB,'index.html'));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Content-Length':body.length});return res.end(body)}json(res,404,{error:'Not found'})}catch(error){json(res,500,{error:error.message})}});
const leaseTimer=setInterval(()=>{const now=Date.now();for(const job of jobs.values())if(job.audioAvailable&&job.leaseUntil<now)release(job)},10000);leaseTimer.unref();
server.listen(PORT,HOST,()=>console.log(`Canary transcription web app v${VERSION} listening on ${HOST}:${PORT} (local: http://127.0.0.1:${PORT})`));
let shuttingDown=false;function shutdown(){if(shuttingDown)return;shuttingDown=true;clearInterval(leaseTimer);for(const job of queue.splice(0)){job.status='cancelled';job.phase='Server stopped';job.endedAt=Date.now();fs.rm(job.file,{force:true},()=>{});notify(job)}const job=running,child=job?.child;if(job){job.status='cancelled';job.phase='Server stopped';job.endedAt=Date.now();notify(job)}if(child){child.kill('SIGTERM');setTimeout(()=>{if(job?.child===child)child.kill('SIGKILL')},1000)}server.close(()=>{fs.rmSync(tempDir,{recursive:true,force:true});process.exit(0)})}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
